Update and rename ncp-update to nettserver-update

diff --git a/bin/nettserver-update b/bin/nettserver-update
--- a/bin/nettserver-update
+++ b/bin/nettserver-update
@@ -1,23 +1,23 @@
 #!/bin/bash
 
-# update latest NextCloudPi code from github
+# update latest NETTSERVER code.
 
 {
   [ "$(id -u)" -ne 0 ] && { printf "Must be run as root. Try 'sudo $0'\n"; exit 1; }
 
-  BRANCH="${1:-master}"
-  [[ "$BRANCH" != "master" ]] && echo "INFO: updating to development branch '$BRANCH'"
+  BRANCH="${1:-server}"
+  [[ "$BRANCH" != "server" ]] && echo "INFO: updating to development branch '$BRANCH'"
 
-  TMPDIR="$( mktemp -d /tmp/ncp-update.XXXXXX || ( echo "Failed to create temp dir. Exiting" >&2; exit 1 ) )"
+  TMPDIR="$( mktemp -d /tmp/nettserver-update.XXXXXX || ( echo "Failed to create temp dir. Exiting" >&2; exit 1 ) )"
   trap "cd /; rm -rf \"${TMPDIR}\"; exit 0" 0 1 2 3 15
 
   echo -e "Downloading updates"
-  git clone --depth 20 -b "$BRANCH" -q https://github.com/nextcloud/nextcloudpi.git "$TMPDIR" || {
+  git clone --depth 20 -b "$BRANCH" -q https://github.com/haraade/nextcloudpi.git "$TMPDIR" || {
     echo "No internet connectivity"
     exit 1
   }
 
-  [[ -f /.ncp-image ]] || cd "$TMPDIR"         # update locally during build
+  [[ -f /.nettserver-image ]] || cd "$TMPDIR"         # update locally during build
 
   echo -e "Performing updates"
   ./update.sh || exit 1
@@ -28,16 +28,16 @@
   # check format
   grep -qP "v\d+\.\d+\.\d+" <<< "$VER" || { "Error: missing version"; exit 1; }
 
-  echo "$VER" > /usr/local/etc/ncp-version
-  echo "$VER" > /var/run/.ncp-latest-version
+  echo "$VER" > /usr/local/etc/nettserver-version
+  echo "$VER" > /var/run/.nettserver-latest-version
 
   # write changelog
   git log --graph --oneline --decorate \
     --pretty=format:"[%D] %s" --date=short | \
     grep 'tag: v' | \
     sed '/HEAD ->\|origin/s|\[.*\(tag: v[0-9]\+\.[0-9]\+\.[0-9]\+\).*\]|[\1]|' | \
-    sed 's|* \[tag: |[|' > /usr/local/etc/ncp-changelog
+    sed 's|* \[tag: |[|' > /usr/local/etc/nettserver-changelog
 
-  echo -e "NextCloudPi updated to version $VER"
+  echo -e "NETTSERVER updated to version $VER"
   exit 0
 } # force to read the whole thing into memory, as its contents might change in update.sh
