Update and rename ncp-check-version to nettserver-check-version

diff --git a/bin/nettserver-check-version b/bin/nettserver-check-version
--- a/bin/nettserver-check-version
+++ b/bin/nettserver-check-version
@@ -1,11 +1,11 @@
 #!/bin/bash
 
-# update latest available version in /var/run/.ncp-latest-version
+# update latest available version in /var/run/.nettserver-latest-version
 
-TMPDIR="$( mktemp -d /tmp/ncp-check.XXXXXX || ( echo "Failed to create temp dir. Exiting" >&2; exit 1 ) )"
+TMPDIR="$( mktemp -d /tmp/nettserver-check.XXXXXX || ( echo "Failed to create temp dir. Exiting" >&2; exit 1 ) )"
 trap "rm -rf \"${TMPDIR}\"; exit 0" 0 1 2 3 15
 
-git clone --depth 20 -q --bare https://github.com/nextcloud/nextcloudpi.git "$TMPDIR" || {
+git clone --branch server --depth 20 -q --bare https://github.com/haraade/nextcloudpi.git "$TMPDIR" || {
   echo "The git clone command failed: No connectivity to https://github.com ?" >&2
   exit 1
 }
@@ -13,13 +13,13 @@ git clone --depth 20 -q --bare https://github.com/nextcloud/nextcloudpi.git "$TM
 cd "$TMPDIR" || exit 1
 VER=$( git describe --always --tags | grep -oP "v\d+\.\d+\.\d+" )
 grep -qP "v\d+\.\d+\.\d+" <<< "$VER" && {       # check format
-  echo "$VER" > /var/run/.ncp-latest-version
+  echo "$VER" > /var/run/.nettserver-latest-version
 
   # write changelog
   git log --graph --oneline --decorate \
     --pretty=format:"[%D] %s" --date=short | \
     grep 'tag: v' | \
     sed '/HEAD ->\|origin/s|\[.*\(tag: v[0-9]\+\.[0-9]\+\.[0-9]\+\).*\]|[\1]|' | \
-    sed 's|* \[tag: |[|' > /usr/local/etc/ncp-changelog
+    sed 's|* \[tag: |[|' > /usr/local/etc/nettserver-changelog
 }
 cd / || exit 1
